services:
  backend:
    build: ./backend
    container_name: ruc-backend
    volumes:
      - db_data:/app/data
      - ./backend/app:/app/app
    environment:
      - DATABASE_URL=sqlite:////app/data/grades.db
      - POLL_INTERVAL=30
      - CIPHER_KEY=Z3JhZGVfbW9uaXRvcl9zZWNyZXRfa2V5XzIwMjU=
      - SMTP_HOST=smtp.qq.com
      - SMTP_PORT=587
      - SMTP_USERNAME=2211399628@qq.com
      - SMTP_PASSWORD=wbnzegvuvnpbeaad
      - SMTP_FROM=2211399628@qq.com
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: ruc-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - vite
    restart: unless-stopped

  vite:
    image: node:20-alpine
    container_name: ruc-vite
    working_dir: /src
    volumes:
      - ./frontend:/src
    command: sh -c "npm install && npx vite --host 0.0.0.0 --port 5173"
    restart: unless-stopped

volumes:
  db_data:
